name: Maven Package

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: temurin
      - name: Read current version
        id: get_version
        run: |
          current_version=$(cat "${{ github.workspace }}/coit-backend1/version/version.txt")
          echo "::set-output name=version::$current_version"

      - name: Increment Version
        id: increment-version
        run: |
          current_version=${{ steps.get-version.outputs.version }}
          IFS='.' read -r major minor patch <<< "$current_version"
          new_version="$major.$minor.$((patch + 1))"
          echo "::set-output name=new-version::$new_version"

      - name: Update Version in version.txt
        run: |
          new_version=${{ steps.increment-version.outputs.new-version }}
          escaped_version=$(echo "${{ steps.get_version.outputs.version }}" | sed 's/[\/&]/\\&/g')
          escaped_new_version=$(echo "$new_version" | sed 's/[\/&]/\\&/g')
          sed -i "s/${escaped_version}/${escaped_new_version}/" "${{ github.workspace }}/coit-backend1/version/version.txt"
         
      - name: Build with Maven
        run: mvn clean install --file "${{ github.workspace }}/coit-backend1"

      - name: Commit version increment
        if: ${{ success() }}
        env:
          PAT: ${{ secrets.PAT_FOR_ACTIONS }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add "${{ github.workspace }}/coit-backend1/**"
          git commit -m "Increment version to ${{ steps.increment-version.outputs.new-version }}" 
      
      - name: Push changes to develop branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: develop
          github_url: https://github.com
          push_to_submodules: on-demand
          directory: .
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.22-7/x64
